[package]
name = "turtle"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]

license = "MIT"
repository = "https://github.com/mneumann/turtle-rs"
description = "Turtle Graphics for Rust"
keywords = ["graphics"]
