[package]
name = "turtle-graphics"
version = "0.1.2-wide"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/mneumann/turtle-graphics-rs"
description = "Turtle Graphics for Rust"
keywords = ["graphics"]
